[General]
language=zh_CN

[License]
# 是否在启动时显示用户登录/授权对话框（true=开启，false=关闭）
EnableStartupCheck=true

[ApplicationUpdate]
ServerUrl=

[MainWindow]
DontConfirmExit=1024
DontConfirmRestart=1024
DontShowDisclaimerMessage=1024

[Modules]
HomeModule=DICOM
FavoriteModules=Data, DICOM, Volumes, SegmentEditor, VolumeRendering, Models

[Styles]
AdditionalPaths=@Invalid()
Style=Dark Slicer

[Internationalization]
Enabled=true
