# -*- coding: utf-8 -*-
"""集成测试用例数据：与《集成测试报告》共用 IT 编号与需求追溯。"""

CASES = [
    {
        "cid": "IT-001",
        "title": "用户登录（成功/失败/锁定）",
        "req": "FR-001/FR-003",
        "module": "用户与权限",
        "pre": "已安装；测试账号；users.db 可写。",
        "steps": "启动→正确登录→退出→连续错误密码至锁定→解锁/重置后再登录。",
        "expected": "成功进入主界面；失败提示；锁定与解锁符合策略。",
        "result": "通过（模拟）",
        "note": "附截图/日志路径（现场填写）。",
    },
    {
        "cid": "IT-002",
        "title": "权限控制（管理员/普通用户）",
        "req": "FR-002",
        "module": "用户与权限",
        "pre": "管理员与普通用户各一。",
        "steps": "普通用户检查管理入口；管理员检查管理入口。",
        "expected": "普通用户不可达；管理员可达。",
        "result": "通过（模拟）",
        "note": "",
    },
    {
        "cid": "IT-003",
        "title": "修改密码",
        "req": "FR-004",
        "module": "用户与权限",
        "pre": "已登录普通用户。",
        "steps": "错误原密码；正确原密码+新密码。",
        "expected": "失败/成功符合规则。",
        "result": "通过（模拟）",
        "note": "",
    },
    {
        "cid": "IT-004",
        "title": "用户管理",
        "req": "FR-005",
        "module": "用户与权限",
        "pre": "管理员登录。",
        "steps": "新增/编辑/禁用/启用/删除（按策略）。",
        "expected": "状态正确且可持久化。",
        "result": "通过（模拟）",
        "note": "",
    },
    {
        "cid": "IT-005",
        "title": "语言切换",
        "req": "FR-010",
        "module": "配置",
        "pre": "默认中文。",
        "steps": "切换英文确认并重启；切回中文。",
        "expected": "持久化且界面正常。",
        "result": "通过（模拟）",
        "note": "",
    },
    {
        "cid": "IT-006",
        "title": "主题切换",
        "req": "FR-011",
        "module": "主题",
        "pre": "AllowThemeSwitch 配置已知。",
        "steps": "允许/禁止场景各验证一次。",
        "expected": "与配置一致。",
        "result": "通过（模拟）",
        "note": "",
    },
    {
        "cid": "IT-007",
        "title": "DICOM 导入成功",
        "req": "FR-020/DR-001",
        "module": "影像",
        "pre": "脱敏 DICOM。",
        "steps": "导入并加载体数据；多视图浏览。",
        "expected": "成功显示。",
        "result": "通过（模拟）",
        "note": "记录耗时 PR-003。",
    },
    {
        "cid": "IT-008",
        "title": "导入校验失败回滚",
        "req": "FR-021/RR-002",
        "module": "影像校验",
        "pre": "不合规样本。",
        "steps": "导入失败样本→检查场景→导入合规样本。",
        "expected": "提示+回滚+可恢复。",
        "result": "通过（模拟）",
        "note": "",
    },
    {
        "cid": "IT-009",
        "title": "影像查看交互",
        "req": "FR-030",
        "module": "可视化",
        "pre": "已导入体数据。",
        "steps": "滚动/缩放/窗宽窗位。",
        "expected": "可用且主观流畅。",
        "result": "通过（模拟）",
        "note": "",
    },
    {
        "cid": "IT-010",
        "title": "医生批注与场景保存",
        "req": "FR-040/DR-005",
        "module": "批注",
        "pre": "可写目录。",
        "steps": "A/B 批注→保存场景→重启加载。",
        "expected": "批注恢复正确。",
        "result": "通过（模拟）",
        "note": "",
    },
    {
        "cid": "IT-011",
        "title": "成果保存/导出",
        "req": "FR-050",
        "module": "输出",
        "pre": "场景有数据。",
        "steps": "保存 MRB/目录；导出（若支持）。",
        "expected": "文件存在可用。",
        "result": "通过（模拟）",
        "note": "",
    },
    {
        "cid": "IT-012",
        "title": "日志记录",
        "req": "FR-060/DR-004",
        "module": "日志",
        "pre": "可写日志。",
        "steps": "触发失败事件；检查日志。",
        "expected": "有记录且脱敏。",
        "result": "通过（模拟）",
        "note": "对照 SR-003。",
    },
    {
        "cid": "IT-013",
        "title": "授权检查（如启用）",
        "req": "FR-070",
        "module": "授权",
        "pre": "开关已知。",
        "steps": "有效/无效各一次。",
        "expected": "符合策略。",
        "result": "通过（模拟）",
        "note": "未启用写 N/A。",
    },
    {
        "cid": "IT-014",
        "title": "壳层净化与白名单",
        "req": "FR-080",
        "module": "壳层",
        "pre": "启动完成。",
        "steps": "检查模块列表与隐藏入口。",
        "expected": "符合产品策略。",
        "result": "通过（模拟）",
        "note": "",
    },
    {
        "cid": "IT-015",
        "title": "配置持久化",
        "req": "FR-090/DR-003",
        "module": "配置",
        "pre": "可控环境。",
        "steps": "修改配置→重启验证。",
        "expected": "持久化正确。",
        "result": "通过（模拟）",
        "note": "",
    },
    {
        "cid": "IT-016",
        "title": "退出与会话",
        "req": "FR-100/RR-003",
        "module": "退出",
        "pre": "已登录。",
        "steps": "退出登录→退出应用→检查日志。",
        "expected": "会话清理；日志完整。",
        "result": "通过（模拟）",
        "note": "",
    },
    {
        "cid": "IT-017",
        "title": "口令存储抽查",
        "req": "SR-002/DR-002",
        "module": "安全",
        "pre": "测试库可查看。",
        "steps": "检查 password_hash 与日志。",
        "expected": "无明文。",
        "result": "通过（模拟）",
        "note": "",
    },
    {
        "cid": "IT-018",
        "title": "启动时间基线",
        "req": "PR-001",
        "module": "性能",
        "pre": "冷启动。",
        "steps": "三次计时中位数。",
        "expected": "满足基线或记录偏差。",
        "result": "通过（模拟）",
        "note": "",
    },
]
